import{a as w,S as P,i as l}from"./assets/vendor-2cfd16ce.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();async function u(t,o){const s="https://pixabay.com/api/",a={key:"43037018-42eeb016e636e06528ba4e47a",q:t,image_type:"photo",orientation:"horisontal",safesearch:"true",page:i,per_page:m};return(await w.get(s,{params:a})).data}const S=document.querySelector(".gallery"),$=new P(".gallery a",{captionsData:"alt"});async function g(t){const o=t.map(({largeImageURL:s,webformatURL:a,tags:e,likes:r,views:n,comments:v,downloads:q})=>`<li class="gallery-item">
            <a class="gallery-link" href ="${s}">
                <img loding="lazy"
                class="gallery-image"
                width="1280" height="152"
                src="${a}"
                data-source="${s}"
                alt="${e}" /></a>
            <ul class="gallery-description">
                <li><h3>Likes</h3><p>${r}</p></li>
                <li><h3>Views</h3><p>${n}</p></li>
                <li><h3>Comments</h3><p>${v}</p></li>
                <li><h3>Downloads</h3><p>${q}</p></li>
            </ul>
        </li>`).join("");S.insertAdjacentHTML("beforeend",o),$.refresh()}const p=document.querySelector(".gallery"),M=document.querySelector(".form"),f=document.querySelector(".loader"),d=document.querySelector(".load-btn");let i=1,c,h,m=15;function y(){f.classList.remove("is-hidden")}function L(){f.classList.add("is-hidden")}M.addEventListener("submit",O);async function O(t){if(t.preventDefault(),p.innerHTML="",i=1,c=t.currentTarget.elements.image.value.trim(),y(),c===""){l.warning({maxWidth:"432px",height:"48px",color:"yellow",position:"topRight",message:"Please fill in the field for search!"});return}try{const o=await u(c,i);o.hits.length===0&&l.error({maxWidth:"432px",height:"48px",color:"red",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),h=Math.ceil(o.totalHits/m),g(o.hits),t.target.reset()}catch(o){console.log(o),l.error({maxWidth:"432px",height:"48px",color:"red",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})}x(),L(),t.target.reset()}function R(){d.classList.remove("is-hidden")}function b(){d.classList.add("is-hidden")}function x(){i>=h?b():R()}function B(){const t=p.firstElementChild.getBoundingClientRect().height;scrollBy({top:t,behavior:"smooth"})}d.addEventListener("click",E);async function E(){i+=1,y();try{const t=await u(c,i);g(t.hits),i>=h&&(b(),l.info({title:"Info",position:"topRight",message:"We are sorry, but you have reached the end of search results."}))}catch(t){console.log(t),l.info({title:"Info",position:"topRight",message:"We are sorry, but you have reached the end of search results."})}B(),x(),L()}
//# sourceMappingURL=commonHelpers.js.map
